config/routes.rb
Rails.application.routes.draw do
  root to: "users#welcome"
  resources :beers do
    member do
      # NHO: little confused why these are namespaced under beers?
      post "add_user" # NHO: looks like a more semantic name for this route / functionality is add_pub  ?
      post "remove_user" # NHO: shouldn't this be a delete request? / is this route being used?
    end
    resources :reviews # NHO: recommend limiting which routes are exposed for a resource...
    # for example, don't think you are using reviews#index
  end
  resources :users
  resource :session
end

app/models/beer.rb
class Beer < ActiveRecord::Base
  has_many :pubs
  has_many :users, through: :pubs
  has_many :reviews # NHO: would recommend adding `dependent: :destroy` to this has_many relationships:
  # so that if any beer is deleted, their associated reviews are also deleted. Prevents "orphan" records
end

app/models/brewerydb.rb
class Brewerydb
  attr_accessor :name, :abv, :ibu, :img_url, :style, :brewery, :location

  def initialize(beer_name)
    # NHO: Do you have to control for case sensitivty / white space at all in this query?
    #url for call to api
    url = "http://api.brewerydb.com/v2/search?q=#{beer_name}&withBreweries=Y&type=beer&key=#{ENV["brewerydb_api_key"]}"

    #make the request
    response = HTTParty.get(url)

    #assign the beer attributes from the first item in the JSON response


    # have to assume users are good
    if response["data"]
      response = response["data"][0]

      # NHO: could simplify these checks with something like: @name = response["nameDisplay"] || "Not Available"
      if response["nameDisplay"]
        @name = response["nameDisplay"]
      else
        @name = "Not Available"
      end

      if response["labels"]
        @img_url = response["labels"]["medium"]
      else
        @img_url = "unavailable.jpg"
      end

      if response["abv"]
        @abv = response["abv"]
      else
        @abv = "Not Available"
      end

      if response["ibu"]
        @ibu = response["ibu"]
      else
        @ibu = "Not Available"
      end

      if response["style"]
        @style = response["style"]["name"]
      else
        @style = "Not Available"
      end

      if response["breweries"][0]["name"]
        @brewery = response["breweries"][0]["name"]
      else
        @brewery = "Not Available"
      end

      if response["breweries"][0]["locations"]
        @location = response["breweries"][0]["locations"][0]["locality"] + ", " +  response["breweries"][0]["locations"][0]["region"]
      else
        @location = "Not Available"
      end
    end
  end
end

app/models/pub.rb
class Pub < ActiveRecord::Base
  belongs_to :user
  belongs_to :beer
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :beer
  belongs_to :user 
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :pubs # NHO: would recommend adding `dependent: :destroy` to this has_many relationships:
  # so that if any user is deleted, their associated pubs are also deleted. Prevents "orphan" records
  has_many :beers, through: :pubs
  has_many :reviews
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :get_current_user

  def get_current_user
    if User.exists?(session[:user_id])
      @current_user = User.find(session[:user_id])
    else
      @current_user = nil
    end
  end
end

app/controllers/beers_controller.rb
class BeersController < ApplicationController
  # NHO: could be worth exploring CanCanCan to help DRY up authorization code
  def index
    @beers = Beer.all
  end

  def new
    if !@current_user
      redirect_to root_url
      flash[:error] = "You must be signed in to do that!"
    end
    @beer = Beer.new
  end

  def create
    redirect_to root_url unless @current_user
    # NHO: confident that part of this code can be moved to the model.
    # Possibly as a custom method that just takes in a new instance of a Brewerydb and returns a Beer instance
    @found_beer = Brewerydb.new(params[:beer][:name])
    # if response does not include a beer flash error
    # @found_beer is always something even if it's properties are nil,
    # so must say if a property exists
    if @found_beer.name
      if !Beer.find_by(name: @found_beer.name)
        @beer = Beer.create!(@found_beer.as_json)
        # go to that beer show page
        redirect_to beer_url @beer
      else
        # go to all beers
        redirect_to beers_url
        flash[:error] = "That beer already exists!"
      end
    else
      # go to all beers
      redirect_to beers_url
      flash[:error] = "Beer not found!"
    end
  end

  def show
    @beer = Beer.find(params[:id])
  end

  def edit
    redirect_to root_url unless @current_user
    @beer = Beer.find(params[:id])
  end

  def update
    redirect_to root_url unless @current_user
    @beer = Beer.find(params[:id])
    @beer.update(beer_params)
    redirect_to beer_url @beer
  end

  def destroy
    redirect_to root_url unless @current_user
    @beer = Beer.find(params[:id]).destroy
    redirect_to beers_path
  end

  def add_user
    @beer = Beer.find(params[:id])
    @beer.pubs.create(user_id: @current_user.id)
    redirect_to user_url @current_user
  end

  private
  def beer_params
    params.require(:beer).permit(:name, :abv, :ibu, :img_url, :brewery, :style, :location)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  # NHO: see note in users controller w/ regards to DRYing up repetitive db calls
  def new
    @beer = Beer.find(params[:beer_id])
    @review = @beer.reviews.new
  end

  def create
    @beer = Beer.find(params[:beer_id])
    @review = @beer.reviews.create!(review_params) # .merge(user: @current_user)
    @review = @review.update(user_id: @current_user.id) # NHO: can do this in one line with by merging in
    redirect_to beer_url @beer
  end

  def edit
    @beer = Beer.find(params[:beer_id])
    @review = @beer.reviews.find(params[:id])
  end

  def update
    @beer = Beer.find(params[:beer_id])
    @review = @beer.reviews.find(params[:id])
    @review.update(review_params)
    redirect_to beer_url @beer
  end

  def destroy
    @beer = Beer.find(params[:beer_id])
    @review = @beer.reviews.find(params[:id]).destroy
    redirect_to beer_url @beer
  end

  private

    def review_params
      params.require(:review).permit(:body)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
  end

  def create
    input_username = params[:user][:username]
    if User.exists?(username: input_username)
      @user = User.find_by(username: input_username)
      if @user.password === params[:user][:password]
        session[:user_id] = @user.id
        redirect_to user_url @user
      else
        flash[:error] = "Wrong Password!"
        redirect_to new_session_url
      end
    else
      flash[:error] = "Username doesn't exist!"
      redirect_to new_session_url
    end
  end

  def destroy
    reset_session
    flash[:notice] = "You have logged out"
    redirect_to :root
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # NHO: One common practice is to abstract all the times you "find" a user/beer/ other resource into a method
  # that is run before a controller action. i.e:
    # before_action :find_beer, only: [:show, :update, :edit, :destroy]
  # of course you would have to define `find_beer` in this example
  
  def new
    @user = User.new
  end

  def create
    @user = User.create!(user_params)
    session[:user_id] = @user.id
    redirect_to user_url @user
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    redirect_to root_url unless @current_user
    @user = User.find(params[:id])
  end

  def update
    redirect_to root_url unless @current_user
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_url
  end

  def destroy
    redirect_to root_url unless @current_user
    @user = User.destroy(params[:id])
    redirect_to new_user_url
  end

  private
    def user_params
      params.require(:user).permit(:name, :username, :email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # NHO: +1 for gravatar!
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/beers/edit.html.erb
<div class="container">

  <h2>Update Beer Info</h2>

  <div class="form">
    <%= form_for @beer do |f| %>
      <%= f.label :name %><br />
      <%= f.text_field :name %><br />

      <%= f.label :abv %><br />
      <%= f.text_field :abv %><br />

      <%= f.label :style %><br />
      <%= f.text_field :style %><br />

      <%= f.label :brewery %><br />
      <%= f.text_field :brewery %><br />

      <%= link_to "Cancel", beer_path %>
      <%= f.submit "Update" %>
    <% end %>
  </div>
</div>

app/views/beers/index.html.erb
<h1>All Beers</h1>

<p class="info">Can't find what you're looking for? <%= link_to "Search", new_beer_path %> for more</p>

<div class="beer-all">
  <% @beers.each do |beer| %>
    <div class="beer-all-container">
      <h2><%= link_to beer.name, beer_path(beer), class: "name-link" %></h2>
      <div class="beer-all-show">
        <%= link_to image_tag(beer.img_url, size: "100x100", class: "label-img"), beer_path(beer) %>
        <div class="beer-all-stats">
          <p><span class="label">Style:</span> <%= beer.style %></p>
          <p><span class="label">ABV:</span> <%= beer.abv %></p>
          <p><span class="label">IBU:</span> <%= beer.ibu %></p>
          <p><span class="label">Brewery:</span> <%= beer.brewery %></p>
          <p><span class="label">Location:</span> <%= beer.location %></p>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/beers/new.html.erb
<div class="container">

  <h2>Search for a Beer!</h2>

  <div class="form">
    <%= form_for @beer do |f| %>
      <%= f.label :name %><br />
      <%= f.text_field :name %><br />

      <%= f.submit "Find Beer" %>
    <% end %>
  </div>
</div>

app/views/beers/show.html.erb
<!-- NHO: formatted code and indentation w/ Atom's Beautify package  -->
<div class="container">
  <h2><%= @beer.name %>
    <span class="edit"><%= link_to("(edit beer info)", edit_beer_path) if @current_user %></span>
  </h2>
  <% if @current_user %>
    <% if !@current_user.beers.include?(@beer) %>
      <!-- NHO: is the second `if @current_user` necessary?  -->
      <%= link_to("Add to my pub", add_user_beer_path(@beer), method: :add_beer) if @current_user %>
    <% end %>
  <% end %>

  <div class="beer-show-container">

    <div class="beer-show">
      <%= image_tag(@beer.img_url, alt: @beer.name, size: "200x200") %>
      <div class="beer-stats">
        <p class="label">Style: <%= @beer.style %></p>
        <p class="label">ABV:<%= @beer.abv %></p>
        <p class="label">IBU:<%= @beer.ibu %></p>
        <p class="label">Brewery:<%= @beer.brewery %></p>
        <p class="label">Location:<%= @beer.location %></p>
      </div>
    </div>
  </div>

  <%= link_to("Add Review", new_beer_review_path([@beer, @review])) if @current_user %>

  <div class="reviews">
    <h2>Reviews:</h2>
    <% @beer.reviews.reverse_each do |review| %>
      <div class="review-body">
        <h3><%= link_to review.user.username, user_path(review.user), class: "name-link" %></h3>
        <p><%= review.body %></p>
        <%= link_to("(edit)", edit_beer_review_path(review.beer.id, review.id)) if @current_user == review.user %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Project2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav>
    <h1><%= link_to "HOPSTR", beers_path %></h1>
    <div class="logo"></div>
  </nav>
  <div class="nav-links">
    <% if @current_user %>
      <%= link_to "#{@current_user.username}", user_path(@current_user) %>
      <%= link_to "Sign out", session_path, method: :delete %>
    <% else %>
      <%= link_to "Sign Up", new_user_path %>
      <%= link_to "Sign In", new_session_path %>
    <% end %>
  </div>

  <% flash.each do |type, message| %>
    <p class="<%= type %>"><%= message %></p>
  <% end %>

  <div class="content">
    <%= yield %>
  </div>

</body>
</html>

app/views/reviews/edit.html.erb
<div class="container">
  <h2><%= @beer.name %></h2>

  <%= image_tag(@beer.img_url, :alt => "@beer.name") %>
  <div class="form">
    <%= form_for [@beer, @review] do |f| %>
      <%= f.label :body, "Review:" %><br />
      <%= f.text_area :body, size: "100x10" %><br />

      <%= f.submit "Update Review" %>
    <% end %>
    <%= button_to("Delete Review", [@beer, @review], method: :delete) %>
  </div>
</div>

app/views/reviews/new.html.erb
<div class="container">
  <h2><%= @beer.name %></h2>

  <%= image_tag(@beer.img_url, alt: @beer.name, size: "200x200") %>
  <div class="form">
    <%= form_for [@beer, @review] do |f| %>
      <%= f.label :body, "Review:" %><br />
      <%= f.text_area :body, size: "100x10" %><br />

      <%= f.submit "Add Review" %>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<div class="container">

  <h2>Update Your Info</h2>

  <div class="form">
    <%= form_for @user do |f| %>
      <%= f.label :name %><br />
      <%= f.text_field :name %><br />

      <%= f.label :username %><br />
      <%= f.text_field :username %><br />

      <%= f.label :email %><br />
      <%= f.email_field :email %><br />

      <%= f.label :password %><br />
      <%= f.password_field :password %><br />

      <%= f.submit "Update Account" %>

    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<div class="container">

  <h2>Sign Up!</h2>

  <div class="form">
    <%= form_for @user do |f| %>
      <%= f.label :name %><br />
      <%= f.text_field :name %><br />

      <%= f.label :username %><br />
      <%= f.text_field :username %><br />

      <%= f.label :email %><br />
      <%= f.email_field :email %><br />

      <%= f.label :password %><br />
      <%= f.password_field :password %><br />

      <%= f.submit "Create Account" %>

    <% end %>

    <p>Have an account? <%= link_to "Sign in", new_session_path %></p>
  </div>
</div>

app/views/users/show.html.erb
<!-- NHO: careful with code formatting / indentation...a little difficult to read  -->
<!-- recommend adding code comments to help break up appropriate sections / label closing divs  -->
<h1>
<%= gravatar_for(@user) %>
<%= @user.username %> <span class="edit"><%= link_to("(edit profile)", edit_user_path) if @current_user == @user %></span></h1>


<h3 class="info">Check out all the <%= link_to "beers", beers_path %> or <%= link_to "search", new_beer_path %> for more</h3>


<div class="pub-container">
  <div class="user-beers-nav">
    <% if @current_user == @user %>
    <h2>My Pub</h2>
    <% else %>
    <h2><%= @user.username %>'s Pub</h2>
    <% end %>
    <% if @user.beers.count == 0 %>
      <p>Your pub is currently empty. <%= link_to("Add some beers!", beers_path) if @current_user == @user %></p>
    <% end %>
  </div>
  <div class="user-beers-all">
    <% @user.beers.each do |beer| %>
      <div class="user-beer">
        <p> <%= link_to beer.name, beer_path(beer), class: "name-link" %> </p>
        <%= link_to image_tag(beer.img_url, size: "150x150"), beer_path(beer) %>
      </div>
    <% end %>
  </div>
</div>

<%= button_to("Delete Account", @user, method: :delete, class: "delete", data: {confirm: "Are you sure?"}) if @current_user == @user %>

app/views/users/welcome.html.erb
<h1 class="welcome">Welcome!</h1>
<div class="welcome-container">



</div>